### PR TITLE
Fix typos for product names

### PR DESCRIPTION
**Pull request by lfrancke**

### CODE REVIEW

**Review by adwk67 — APPROVED** [review]

**Comment by lfrancke** [comment]
Thanks Andrew.
@siegfriedweber (and I) aren't sure if this can just be updated or if this will lead to new entries in the Operator catalog?

**Comment by adwk67** [comment]
I deployed a corrected version (dummy release 24.10.0-1) over an existing 24.7.0 and it looks OK (i.e. only one version of the operator:

image

(this was done with the catalogs, though, not the certification)

**Comment by lfrancke** [comment]
Thank you!
So......I'd be willing to take the risk. That said: This is not urgent and I'd suggest we wait until next week to see if @razvan has any input?

**Comment by razvan** [comment]
LGTM.

The issue doesn't mention where exactly the typos were seen and I assume it was the detailed description page and not the overview page,

I believe the overview page (as shown in the screenshot) for the certified ops is not generated from scripts (CSVs) but from  the RH portal. These entries look fine to me. Here is ZooKeeper:
image

Also the cert pipeline will reject duplicate entries so we cannot update the detailed descriptions of existing op versions.

This change will take effect for next versions.

**Comment by lfrancke** [comment]
We saw them in the catalog itself. Customer shared their screen, looked in the catalog, searched for Stackable

**Pull request merged**
